### ISSUE TITLE
(When AGP 3.0 is released) Java 8 and assume desugar for android, or target Java 7?

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#10]
Need to make a call on this based on our integration and see how it fairs using this in Java 7 source.

**Comment by hzsweers** [comment]
With desugar coming to the android toolchain, should we move to Java 8 and assume people will use desugar?

**Comment by vinc3m1** [comment]
I would wait until stable release, but after that sure.

**Comment by tonycosentini** [comment]
What benefit does it give the library?

It seems like for consumers it adds a bit of friction for using this, no?

**Comment by hzsweers** [comment]
It makes the library easier to read/write in by using the new syntax features. From a java library distribution standpoint - everyone writing a pure java project these days should really be on Java 8. On Android, with desugar, it should be zero friction since it all gets done at dexing.

**Comment by LukeStClair** [comment]
It's really not in a stable place yet though, right? At least in trying to
use it myself, I had to turn it off eventually because of all the issues I
ran into. It also requires alpha plugins to work correctly, no?

**Comment by hzsweers** [comment]
I should have clarified - *when android gradle plugin 2.4 stable is released, not immediately.

**Comment by digitalbuddha** [comment]
I'm not sure if you can assume that everyone will upgrade to 2.4 stable as soon as it is released. What is the downside of using Retrolambda until better adoption of newer tools?

**Comment by hzsweers** [comment]
In testing with this, I found that consuming retrolambda'd libraries in Java 7 projects (retrolambda'd or not) actually added quite a bit of friction. Due to how the weaving works, you get no sources (only decompiled class files), and trying to step through them in the debugger is pretty hit or miss. Not to mention you can't actually open said generated classes due to not having sources, so you can't just go open them and set a breakpoint manually either :|.

The desugar approach they're taking with the gradle plugin actually works around this by treating the entire project as java 8 until you compile, at which point it will also desugar any Java 8-targeting libraries compiled with it.

**Comment by hzsweers** [comment]
Another potential benefit: LifecycleScopeProvider could be moved to a separate (optional) artifact if we support default methods. It could just extend ScopeProvider and the default `requestScope()` method would do the swizzling with a default implementation.

This works fine for android gradle projects, but could incur a nontrivial cost for buck/bazel builds where incremental compilation can't work some magic.

**Comment by hzsweers** [comment]
Opened an issue on bazel to better understand how they avoid clean build churn - https://github.com/bazelbuild/bazel/issues/4186

**Comment by hzsweers** [comment]
Closing in favor of #198
