### ISSUE TITLE
Removing synthetic accessors

### ISSUE THREAD

**Issue by bangarharshit** [uber/AutoDispose#102]
There is around 27 synthetic accessors method (most of which are in tests).  RecordingObserver, AutoDisposingSubscriberImpl (and similar classes) has around 12 methods. Maybe convert them to package protected to reduce dex count by 12.

**Comment by hzsweers** [comment]
want to send a proposal PR? Can't promise all of them for API reasons but would want to see what the scope is.

**Comment by bangarharshit** [comment]
Created a PR. Also verified that proguard is not inling the methods.

**Comment by bangarharshit** [comment]
Closing since it is merged. All the other synthetic accessors are in tests and which can be safely ignored.
