### ISSUE TITLE
bindUntilEvent with architecture components

### ISSUE THREAD

**Issue by rubengees** [uber/AutoDispose#104]
Version: `0.3.0`

I was previously using `RxLifecycle` and played around a bit with `AutoDispose`. So far it works great, but i miss the `bindUntilEvent` method from `RxLifecycle`.
I have seen the other [issue](https://github.com/uber/AutoDispose/issues/72) about this, but could not manage to get it to work, especially when using architecture components integration...
Some samples or even better, a first class api would be very appreciated.

My current `RxLifecycle` code looks like this:

```kotlin
errorButton.clicks()
    .bindUntilEvent(this, Lifecycle.Event.ON_DESTROY)
    .subscribe {
        // Do something.
     }
```

Thanks in advance!

**Comment by hzsweers** [comment]
Hmmm, I suppose we could have an overload for `from` that accepts a target event and just filters on that. Interested in contributing a PR? If not I can get around to it this week

**Comment by hzsweers** [comment]
Done in #107
