### ISSUE TITLE
Dokka for kotlin artifacts

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#122]
https://github.com/Kotlin/dokka

**Comment by Kietzmann** [comment]
I'm on it

**Comment by hzsweers** [comment]
Thanks! Keep us posted how it goes

**Comment by hzsweers** [comment]
Thanks! Keep us posted how it goes

**Comment by Hackertronix** [comment]
@hzsweers I am trying to give this a shot but I am getting issues importing the project into IntelliJ
![screen shot 2017-10-25 at 11 06 33 am](https://user-images.githubusercontent.com/5685314/31982307-d3252812-b975-11e7-8226-bc6a5c8c264f.png)

**Comment by Kietzmann** [comment]
@Hackertronix 
You must install android sdk

**Comment by hzsweers** [comment]
yep, or just comment out the android modules in `settings.gradle`

**Comment by Hackertronix** [comment]
@kietzmann @hzsweers I already have the SDK installed and configured.... My ANDROID_HOME path is also set up even then i'm getting this

**Comment by hzsweers** [comment]
Even if you just comment out those modules from settings.gradle?

**Comment by hzsweers** [comment]
Or I suppose you might want to have those synced to wire up dokka for the Android javadoc tasks too. I'm not sure other than trying to restart your IDE or to add to to a local.properties file in your project dir

**Comment by charlesdurham** [comment]
@Kietzmann any updates? :)

**Comment by Kietzmann** [comment]
@charlesdurham 
Hi, I faced some issues when building the project. Currently busy and won't have free time for this next week.

**Comment by charlesdurham** [comment]
@Kietzmann would you mind if I looked at the issue in the meantime?

**Comment by Kietzmann** [comment]
No, I wouldn't

2017-11-05 16:05 GMT+02:00 Charles Durham <notifications@github.com>:

**Comment by hzsweers** [comment]
This is done in #126
