### ISSUE TITLE
Proposal: Split android into separate project

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#131]
Currently, autodispose is all one big project with multiple modules.

While this is convenient, we currently cannot updated to AGP 3.0 because it requires Android Studio (something we don't want to impose on people). Thing is though, by having android in the build every time anyway, we require the android sdk already. This has been a point of friction a couple of times already for contributors. 

Options:

1. Keep as is, make android buildability required
    * Pros:
      * Nothing changes, we just make it explicit this requires Android Studio + SDK to use. Might be ok if IntelliJ 2017.3 updates their Android support to pull in AGP 3 changes
    * Cons:
      * Android sdk still required to build, even if not using it. Can be inconvenient
2. Separate android to a separate build, but keep it in the same repo. This means that it still lives here, but is a functionally separate entity. It would need to depend on AutoDispose as a public artifact.
    * Pros: 
      * Still lives here, accessible
    * Cons: 
      * build friction/overhead for those that want to build android
      * awkward tooling experience
      * A new non-android java/kotlin sample would need to be written.
      * Releases are awkward to synchronize
3. Extract android components to a completely separate repo, make it fully independent extensions
    * Pros:  
      * Easier to reason about and maintain
      * none of the tooling issues of option 2
      * Releases are independent
    * Cons: 
      * Separate repo! But maybe that's ok. 
      * Duplicate code for things like test utils
      * A new non-android java/kotlin sample would need to be written.
      * Releases are independent
      * If android is separate, should kotlin? Thinking not (analogues exist for both java and android)

**Comment by hzsweers** [comment]
Currently, I'm leaning toward option 3.

Seeking thoughts, so CCing @tyvsmith @jbarr21 @LukeStClair

**Comment by hzsweers** [comment]
Another consideration - protecting commit history, specifically so that external contributors remain recognized

**Comment by tyvsmith** [comment]
because it *currently* requires Android Studio.

Let's figure out Google/Idea roadmaps for this constraint before taking on a large undertaking to segment this repo. If this is a short term problem, we should wait on upgrading. The improvements given by AGP 3.0 will be minimal anyway, since most folks are consuming the artifacts, not building this directly.

**Comment by hzsweers** [comment]
It also requires the android sdk to build, which burned at least a couple people

**Comment by tyvsmith** [comment]
What about conditionally pulling in the Android projects in settings.gradle if $ANDROID_HOME is set, or some other indicator. I think the IDEs would still handle this normally.

**Comment by hzsweers** [comment]
hmm, that's an idea. Kind of wish AGP would expose an API to check that sanely since it can leverage other heuristics too
