### ISSUE TITLE
Support ParallelFlowable

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#142]
ParallelFlowable is considered a 6th distinct type in RxJava, complete with its own `as()` operator. We should probably support it.

Scope would be:
* Add to AutoDisposeConverter's supported interfaces
* Add extension functions to kotlin (no need for a deprecated `autoDisposeWith()` version
* Implementation, though I think we can just return `AutoDisposingSubscriberImpl`
  * If we do reuse it, we should add a `isParallel()` method so consumers can introspect it.

**Comment by VisheshVadhera** [comment]
Hey, can I open a PR for this one?

**Comment by hzsweers** [comment]
Please do!

**Comment by VisheshVadhera** [comment]
Hey, @hzsweers, do you believe there's a use case for `isParallel()` in `AutoDisposingSubscriberImpl`?

**Comment by hzsweers** [comment]
let's leave it out for now
