### ISSUE TITLE
Add error-prone DoNotMock annotations to elements with test helpers

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#146]
After fixing a bunch of cases where bad mockito usage broke tests during the last update, I think we should introduce these.

Anything with a test component should get this annotation and point to its test component.

* `ScopeProvider` -> `TestScopeProvider`
* `LifecycleScopeProvider` -> `TestLifecycleScopeProvider`

The error-prone annotations themselves should be `compileOnly` or `provided`

**Comment by bangarharshit** [comment]
I can work on it. Do you also expect [positive/negative](https://github.com/google/error-prone/wiki/Writing-a-check#exercise-5-positive-cases-example-solution) test cases?

**Comment by hzsweers** [comment]
No need for tests, just the annotations will do

**Comment by hzsweers** [comment]
Done in #153
