### ISSUE TITLE
Code formatter tool to adhere to checkstyle

### ISSUE THREAD

**Issue by bangarharshit** [uber/AutoDispose#154]
[uber/NullAway](https://github.com/uber/NullAway/blob/master/config/hooks/pre-commit) uses a pre-commit hook to format code to google Java style. Can be pretty useful to contributors as they don't have to worry about styling.

**Comment by hzsweers** [comment]
does it require the user to manually install it? I'd been leaning toward using Spotless since that also covers kotlin

**Comment by bangarharshit** [comment]
It doesn't require anything for manual installation. It is just a [Gradle plugin](https://github.com/sherter/google-java-format-gradle-plugin). In `NullAway` it is in root [build.gradle](https://github.com/uber/NullAway/blob/master/build.gradle#L18). 

`Spotless` looks much more customizable though and is a superset of the Gradle plugin.

**Comment by hzsweers** [comment]
yeah I think I'd rather spotless. This project doesn't use google's style guide anyway :). It's similar but with some changes (I don't like how GJF handles lambdas and always multilines field annotations)

**Comment by VisheshVadhera** [comment]
@hzsweers @bangarharshit Can I open a PR for this one?

**Comment by hzsweers** [comment]
I'll handle this one, I've bee prototyping it in another repo to iron out issues. Thanks though!

**Comment by VisheshVadhera** [comment]
Sounds good!

**Comment by VisheshVadhera** [comment]
@hzsweers Any other way by which I can contribute to this project?

**Comment by hzsweers** [comment]
You could look at #181 if you want, just drop a comment first asking if anyone else is already working on it, and if no one responds by tomorrow, I'd say go for it :)
