### ISSUE TITLE
New plugin hook for main thread checks 

### ISSUE THREAD

**Issue by ZacSweers** [uber/AutoDispose#181]
Currently, main thread checks are not configurable. In testing though, this can be a nuisance if you're trying to run in a JVM test. We've currently covered this case by just try/catching the check, but that's obviously a little wonky. A useful plugin for this would be to allow for replacing the check with your own.

From a design standpoint, the plugin would live in the `autodispose-android` artifact, and should just be modeled after [RxAndroid's plugins setup](https://github.com/ReactiveX/RxAndroid/blob/2.x/rxandroid/src/main/java/io/reactivex/android/plugins/RxAndroidPlugins.java).

The checker would be a `Callable<Boolean>` implementation. The default one can live as a static singleton instance in `AutoDisposeAndroidUtil` and initialized the [same way](https://github.com/ReactiveX/RxAndroid/blob/2.x/rxandroid/src/main/java/io/reactivex/android/schedulers/AndroidSchedulers.java#L27-L37) to avoid class loading (this is key so people can swap in their own impl before the `Looper` code is hit).

Method would still be `isMainThread()` in the util class, but it would defer to calling the plugin hook.

All in all, from a high level, it would look like this:

AutoDisposeAndroidUtil.java
```java
private Callable<Boolean> MAIN_THREAD_CHECK = new Callable<Boolean>() {
    @Override public Boolean call() throws Exception {
        return Looper.myLooper() == Looper.getMainLooper();
    }
}

public static boolean isMainThread() {
  return AutoDisposeAndroidPlugins.onCheckMainThread(MAIN_THREAD_CHECK);
}
```

AutoDisposePlugins.java
```java
public static boolean onCheckMainThread(Callable<Boolean> mainThreadChecker) {
  if (mainThreadChecker == null) {
    throw new NullPointerException("mainThreadChecker == null");
  }
  Callable<Boolean> c = onCheckMainThread;
  try {
    if (c == null) {
      return mainThreadChecker.call();
    } else {
      return c.call()
    }
  } catch (Exception ex) {
    throw Exceptions.propagate(ex);
  }
}

// setOnCheckMainThread(...)
// reset()
```

I don't _think_ we need the init methods their plugins impl has, but can evaluate as needed.

**Comment by VisheshVadhera** [comment]
I would love to open a PR for this one, if no one else has started work yet.

**Comment by hzsweers** [comment]
I think you're good to go if you want to take a crack at this @VisheshVadhera!

**Comment by hzsweers** [comment]
@VisheshVadhera do you still plan to do this? Otherwise I'll tackle it this week

**Comment by hzsweers** [comment]
Cool, sounds good!

**Comment by hzsweers** [comment]
@ VisheshVadhera in the interest of time, I'm going to work on this first part of this week, as we want to get another release out middle of this week

**Comment by VisheshVadhera** [comment]
@hzsweers Apologies. Been busy with work over the past couple of weeks. I'll definitely get back to closing some of the other issues in future and maybe add some too! :)
