### ISSUE TITLE
Refactor converters to be the native implementation, make old to() APIs delegate to them.

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#188]
So currently, every `as()`-based converter API just wraps the old `to()`-based scoper APIs. This works, but in 1.0 we're going to want to remove the old `to()` based APIs, so as an intermediary let's flip this in 0.8.0. This release'll be a non-API changing release, and totally just flip these internals as an incremental update.

These can/should be done incrementally, and should be modeled after parallelflowable's implementation. It's ok if the scopers are a bit verbose in the meantime or even duplicated functionality. The main goal here is to get the `as()` APIs fully migrated so that 1.0 is just removing the old scopers. No tests or extension artifacts (android, rxlifecycle) should be changed in this process to ensure the public API is not changing.

- [x] `ObservableConverter`/`ObservableScoper`
- [ ] `SingleConverter`/`SingleScoper`
- [ ] `MaybeConverter`/`MaybeScoper`
- [x] `CompletableConverter`/`CompletableScoper`
- [ ] `FlowableConverter`/`FlowableScoper`

**Comment by hzsweers** [comment]
I'll do one of these initially to set a guideline, then try to leave the rest up for some contributors (I know there's a few people interested)

CC @atexannamedbob @VisheshVadhera @tyvsmith

**Comment by hzsweers** [comment]
First one is up in #189. Once that's merged, others should feel free to claim remaining ones

**Comment by VisheshVadhera** [comment]
@hzsweers #189 looks great. Would love to open a PR for the remaining ones, once the the first one gets merged.

**Comment by hzsweers** [comment]
First one is down and stencil is in place. @VisheshVadhera if you could just pick one to start, want to leave the rest for others to pick up if interested :)

**Comment by VisheshVadhera** [comment]
I'll pick SingleObserver.

**Comment by atexannamedbob** [comment]
@hzsweers @VisheshVadhera 
I'll take on 
MaybeConverter/MaybeScoper
and
CompletableConverter/CompletableScoper

**Comment by hzsweers** [comment]
I'm going to move forward with this so we can isolate the next release around it. @VisheshVadhera I'll do SingleObserver last in case you have time to come around to it, but going to do this in the next few days

**Comment by VisheshVadhera** [comment]
@hzsweers Sounds good. I'll open the PR for SingleObserver tonight!

**Comment by hzsweers** [comment]
This is done now
