### ISSUE TITLE
AutoDispose does not handle Fragment onDestroyView

### ISSUE THREAD

**Issue by jinatonic** [uber/AutoDispose#192]
Unsure if this only applies to `onDestroyView` because support fragment does some funky state manipulation, e.g. (taken from support fragment source code)

```java
void performReallyStop() {
    if (mChildFragmentManager != null) {
        mChildFragmentManager.dispatchReallyStop();
    }
    mState = ACTIVITY_CREATED;
}

void performDestroyView() {
    if (mChildFragmentManager != null) {
        mChildFragmentManager.dispatchDestroyView();
    }
    mState = CREATED;
    mCalled = false;
    onDestroyView();
    ...
}
```

Anyway, the following code causes autodispose to not crash or ever dispose of the observable.

```kotlin
override fun onDestroyView() {
    super.onDestroyView()

    Observable.interval(1, TimeUnit.SECONDS)
            .`as`(AutoDispose.autoDisposable<Long>(AndroidLifecycleScopeProvider.from(this)))
            .subscribe {
                println("Subscribed! $activity")
            }
}
```

From some initial debugging, it looks like autodispose thinks that the current lifecycle is `onStart` (which i guess makes sense because `LifecycleEventsObservable.backfillEvents` maps the state `ON_CREATE` to `ON_START`, and from looking at the fragment's code it looks like the state would be created.

**Comment by hzsweers** [comment]
Interesting. I'm fairly busy this week and then traveling for a couple weeks, so it might be awhile before I can properly dive into this :/. Will try to float it by some fragment-familiar friends to see if they have any ideas

**Comment by hzsweers** [comment]
Actually, I think I've got a solution. Will put up a PR in a bit
