### ISSUE TITLE
Lint API artifact

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#203]
Alongside the error-prone tooling option, we want to add a lint option as well. This is more flexible than the error prone option and shows up in the IDE nicely.

The linter should work for both kotlin and java code, and thus also check both kotlin and java autodispose APIs. By default it should be an error.

The linter should offer a quick fix in the appropriate language API if possible (not sure how doable this is since we need to ask the user for a "scope")

It should be written in Kotlin, as it will be using UAST and this is the recommendation of the lint maintainers at Google.

This depends on #190

**Comment by shaishavgandhi05** [comment]
What kind of Lint checks do we have in mind? 

Might be useful to have something like [this](https://github.com/square/sqlbrite/issues/58) which has a checklist.

**Comment by hzsweers** [comment]
This is done in #282!
