### ISSUE TITLE
When the activity is put in the background, it will cancel the subscription

### ISSUE THREAD

**Issue by tcqq** [uber/AutoDispose#207]
Hello, thanks your library, I use the following code, the effect I want to achieve is to cancel the subscription after the current activity is destroyed, this effect has been achieved, but I found a problem, 

`AutoDispose.autoDisposable(AndroidLifecycleScopeProvider.from(this))`

when activity put into the background it will also cancel the subscription, this caused my current network request to be cancelled
![image](https://user-images.githubusercontent.com/10644057/39706964-94ccc98a-5245-11e8-9a03-6f8410e947eb.png)

, I am currently using this method to fix the above problem
`AutoDispose.autoDisposable(AndroidLifecycleScopeProvider.from(this, Lifecycle.Event.ON_DESTROY))`

**Comment by hzsweers** [comment]
If you're binding after onResume, it will stop in onPause. Is that what's happening in this case?

**Comment by tcqq** [comment]
If this is the case, when I return to the application from the background, it will re-subscribe.

**Comment by hzsweers** [comment]
I think you'd have to model it in such a way that you don't always subscribe in onResume if you don't want to unsubscribe in onPause

**Comment by tcqq** [comment]
Yes, but now with this default code`AutoDispose.autoDisposable(AndroidLifecycleScopeProvider.from(this))`, when "onPause"time it will cancel the subscription, this situation is rarely used, So I suggest to modify the default configuration, do not cancel the subscription when the activity is paused

**Comment by tcqq** [comment]
All right.

**Comment by wjbd** [comment]
How to do not cancel the subscription when the activity is paused？

**Comment by hzsweers** [comment]
It depends. If you're using the arch components support and subscribing during onResume, you can set an `[untilEvent](https://github.com/uber/AutoDispose/blob/bec9987297dbc40a6cf88f91636fec2fe3111823/android/autodispose-android-archcomponents/src/main/java/com/uber/autodispose/android/lifecycle/AndroidLifecycleScopeProvider.java#L101)` to target something other than the default corresponding `onPause`. If you're doing something custom, you'll have to manually specify it in your custom scope.

**Comment by wjbd** [comment]
Thanks
I see
