### ISSUE TITLE
No support for AndroidX Lifecycle

### ISSUE THREAD

**Issue by Nominalista** [uber/AutoDispose#209]
**0.8.0**:

Since there are two `LifecycleOwner`'s, one from `android.arch.lifecycle` and another one from `androidx.lifecycle`, it's impossible to use e.g. Fragment in `AndroidLifecycleScopeProvider`.

I'm wondering if `autodispose-android-archcomponents` will be migrated to AndroidX.

**Comment by hzsweers** [comment]
It will be migrated when the androidx libraries are stable. Please use the Jetifier tool that was released to bridge external libraries
