### ISSUE TITLE
Handling Orientation Change Example

### ISSUE THREAD

**Issue by goransipic** [uber/AutoDispose#217]
Hi,

What's about orientation change. Do you handle that case with library.

**Comment by hzsweers** [comment]
That's more of an architecture question. If you were using the viewmodel architecture component, you'd expose an RX API to get your data from the viewmodel and only use autodispose to dispose your subscription in the activity in onDestroy and resubscribe after. Perhaps it'd be useful if we added a demo for that in the sample?

**Comment by shaishavgandhi05** [comment]
One suggestion for the samples is to organize them the way the modules are organized. Usually, on reading the Readme, one has an idea about the module they're gonna use. It would be useful to have a structure like:
-sample
  - android-arch
  - android-arch-kotlin (or android-arch can have both java and kotlin just the way it is now)
  - rxlifecycle
  
This leaves room for further modules as well and makes the samples easy to navigate.

**Comment by goransipic** [comment]
Demo example would be a good way to show how to Handle Orientation Change Scenario. Maybe a can help you with demo. Thanks for great library! @hzsweers

**Comment by hzsweers** [comment]
Sample contributed in #223
