### ISSUE TITLE
Investigate alternative CI solutions

### ISSUE THREAD

**Issue by ZacSweers** [uber/AutoDispose#220]
Travis takes so long for android tests, would like to explore this more.

**Comment by shaishavgandhi05** [comment]
I use CircleCI in most of my projects and I find it great. It's really fast and configuration is simpler. 

One caveat is that CircleCI 2.0 doesn't really support [testing on emulator](https://support.circleci.com/hc/en-us/articles/360000028928-Testing-with-Android-emulator-on-CircleCI-2-0). They seem to be recommending using Firebase Test Lab.

**Comment by hzsweers** [comment]
interesting... the lack of emulator support is frustrating :|, as that's the main thing that makes travis slow for this project.

Have any example configs you could point me to? Never used it personally, and our only other project using it (okbuck) doesn't have an android configuration for it afaik

**Comment by shaishavgandhi05** [comment]
Here's a [configuration](https://github.com/shaishavgandhi05/navigator/blob/master/.circleci/config.yml) from one of my projects. It's pretty much what they recommend in their [guide](https://circleci.com/docs/2.0/language-android/#sample-configuration).

**Comment by hzsweers** [comment]
Thanks!
