### ISSUE TITLE
Integrate codecov

### ISSUE THREAD

**Issue by ZacSweers** [uber/AutoDispose#222]
There's a few different facets to this:

- kotlin code coverage
- android code coverage (both instrumentation and unit tests)
- java code coverage
- exclude generated lifecycle adapter

And then collect these all together under a single root `codeCoverageReport` task

**Comment by nehalsep7** [comment]
Is this task up for grab?

**Comment by ZacSweers** [comment]
Sure!

**Comment by ZacSweers** [comment]
I can't do this now that I'm outside of the Uber org, so someone at Uber will need to take this up

**Comment by sherrif10** [comment]
@ZacSweers  i would like to work on this issue , however according to your comment above does it need someone from uber org to push this commit

**Comment by ZacSweers** [comment]
Right, this can't be externally contributed unfortunately

**Comment by sherrif10** [comment]
thanks for your updates

**Comment by ZacSweers** [comment]
I took a crack at wiring together code coverage but honestly I don't see much value in this. Jacoco + Gradle in a multi-module project, let alone with kotlin and android, seems a fool's errand
