### ISSUE TITLE
Android-lifecycle-ktx extensions should return ScopeProvider

### ISSUE THREAD

**Issue by shaishavgandhi05** [uber/AutoDispose#239]
**Library version**: 1.0.0-RC1

This is more of a question than a suggestion. With 1.0.0-RC1, the overloads to `autoDisposable` have been reduced to `Completable` and `ScopeProvider`. 

In `AutoDisposeAndroidLifecycle.kt`, the extensions still return a `LifecycleScopeProvider<*>`. Should this also be changed to `ScopeProvider` since `LifecycleScopeProvider` extends `ScopeProvider`?

**Comment by hzsweers** [comment]
Good idea, and keeps it open to flexibility in the future. Want to send a PR?

**Comment by shaishavgandhi05** [comment]
Yup sounds good!

**Comment by shaishavgandhi05** [comment]
This was resolved with #240
