### ISSUE TITLE
Access to `autoDisposable` extension with arch-components-ktx

### ISSUE THREAD

**Issue by shaishavgandhi05** [uber/AutoDispose#241]
**Library version**: 1.0.0-RC1

This is more of a proposal/discussion. 

AutoDispose does a great job of separating artifacts so that they can be used in conjunction with each other.

I wanted to float a proposal to include `autodispose-ktx` with `android-arch-components-ktx`. With this change, the user(Android specific) would only have to include the `android-arch-components-ktx` artifact. 

Besides being convenient, this makes sense in some ways. 

1. A consumer who is importing the `arch-components-ktx` artifact is likely a Kotlin user and will inherently want to use the other `ktx` artifacts.
2. This is further supported by the fact that the `as` operator (which you would use if you're not using `autodispose-ktx`) is clunky in Kotlin since you have to wrap it with the `. 
3. The method count of adding `autodispose-ktx` is pretty low. It's basically a few extension functions. 

To be consistent, we might have to also include `autodipose-ktx` with `autodispose-android-ktx`.

**Comment by hzsweers** [comment]
I think I'm against this. It would be adding a dependency out of convenience, but not because it's actually used

**Comment by shaishavgandhi05** [comment]
It would actually be used in lots of cases. I don't have data backing this up but it seems intuitive to use the `autoDisposable` extension at the end of the RxJava chain instead of \`as\` in Kotlin. And since they're using `arch-components-ktx`, they're already Kotlin users.  

However, I can understand where you're coming from. It doesn't feel exactly right given that it's a dependency the user didn't explicitly ask for and there is a chance they may never end up using it. Closing this.
