### ISSUE TITLE
AutoDisposing ViewModel Recipe

### ISSUE THREAD

**Issue by shaishavgandhi05** [uber/AutoDispose#253]
**Library version**: 1.0.0-RC2

When you're using RxJava, one common use-case with the Architecture Components `ViewModel` is that you subscribe to a stream of data in the ViewModel itself. This is beneficial say in making a network request that's in flight. Since you're subscribing in the ViewModel, the request will still get completed. You then link your ViewModel to the View with a `LiveData` or something like a `BehaviorRelay`. In such cases you'll dispose of your `Disposable` using a `CompositeDisposable` in the ViewModel and calling `dispose` in the `onCleared` of the ViewModel. 

This is a good place to bring in AutoDispose by creating a base ViewModel which implements `LifecycleScopeProvider` and automatically disposes the subscription in `onCleared`.

I have a working example which I've tested and I'd definitely like to add it to the recipes in the `sample` project. 

Another proposal (which I believe this project wouldn't go for, but hey I'll try), would be to include this recipe as part of the `arch-components` module or a separate module of it's own that can be easily imported.

**Comment by hzsweers** [comment]
Let's start with a proposal PR to add it to the sample, not totally sure I followed this

**Comment by hzsweers** [comment]
Done in #254
