### ISSUE TITLE
can i use compose() ?  i need a Observable instance

### ISSUE THREAD

**Issue by qq2748** [uber/AutoDispose#255]
**Library version**:

**Repro steps or stacktrace**:

**Comment by qq2748** [comment]
like the rxlifecycle:

> @SuppressWarnings("unchecked")
        @Override
        public Observable adapt(@NonNull Call<R> call) {
            Observable compose = wrapped.adapt(call).compose(new ErrorTransformer(call, errorMsgMap));
            if (lifecycleProvider != null) {
                if (lifecycleProvider instanceof Activity) {
                    compose = compose.compose(lifecycleProvider.bindUntilEvent(ActivityEvent.DESTROY));
                } else if (lifecycleProvider instanceof Fragment || lifecycleProvider instanceof android.app.Fragment) {
                    compose = compose.compose(lifecycleProvider.bindUntilEvent(FragmentEvent.DESTROY));
                }
            }
            return compose;
        }

**Comment by qq2748** [comment]
Because I want to be unified outside, so I don't need to call each other once

**Comment by hzsweers** [comment]
Nope! By design, autodispose has to be last call in the chain. Otherwise it cannot abide by the contracts of the types it supports (I.e. you could end up with an observable downstream that never terminates)

**Comment by qq2748** [comment]
Thanks a lot.
