### ISSUE TITLE
D8: Invoke-customs are only supported starting with Android O (--min-api 26)

### ISSUE THREAD

**Issue by joshfriend** [uber/AutoDispose#265]
**Library version**: 1.0.0

**Repro steps or stacktrace**:

Environment:

* Gradle 4.10.2
* Android Gradle Plugin 3.2.1 (also duplicated with 3.2.0)
* Android build tools 28.0.3
* Kotlin 1.2.71

Upgrading autodispose from 1.0.0-RC2 to 1.0.0 results in build failures when using R8 to generate a minified build:

```
> Task :app:transformClassesAndResourcesWithR8ForDebugMinified
D8: Invoke-customs are only supported starting with Android O (--min-api 26)

> Task :app:transformClassesAndResourcesWithR8ForDebugMinified FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithR8ForDebugMinified'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete
```

**Comment by joshfriend** [comment]
I tried adding this to the toplevel app's `build.gradle`:

```groovy
compileOptions {
  sourceCompatibility JavaVersion.VERSION_1_8
  targetCompatibility JavaVersion.VERSION_1_8
}
```

which worked, but is there a way to avoid that?

**Comment by hzsweers** [comment]
AutoDispose is a Java 8 library, with the expectation that consumers are using Java 8-targeting android apps and D8/desugar tools as needed for supporting older versions of android that don't support java 8

Per the changelog here: https://github.com/uber/AutoDispose/blob/master/CHANGELOG.md#version-100-rc3

Basically - there's no reason not to use the source/target compatibility you listed + D8 on android projects as of android gradle plugin 3.2.0.
