### ISSUE TITLE
1.0.0 LifecycleOwner

### ISSUE THREAD

**Issue by quert999** [uber/AutoDispose#268]
LifecycleOwner was replaced by androidx.lifecycle.LifecycleOwner.
is that a bug?

**Comment by shaishavgandhi05** [comment]
Have you moved to Android Jetpack? All Android Jetpack libraries have moved to a new package name. The `androidx.lifecycle.LifecycleOwner` is the new package of the `LifecycleOwner`. If you haven't moved to Jetpack yet then then you can stick to the `1.0.0-RC3` release and update to 1.0.0 when your app moves to Jetpack.

**Comment by quert999** [comment]
oh, I see, thank you.

**Comment by 1step2hell** [comment]
This should be wrote in fxxking README, waste too much time.
