### ISSUE TITLE
stackOverflowError

### ISSUE THREAD

**Issue by q805699513** [uber/AutoDispose#273]
BActivity

init(){
openCell();
}   

 AtomicInteger times = new AtomicInteger();

 private void openCell() {
       // Hal.getInstance().getDriver().openCell(getSpinCabinetNum(), getCellNum())
Flowable.just(new Object())
                .delay(3000, TimeUnit.MILLISECONDS)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .doFinally(() -> {
                    if (times.get() < 1000) {
                        openCell();
                    }
                })
                .as(AutoDispose.autoDisposable(AndroidLifecycleScopeProvider.from(this)))
                .subscribe(o -> {
                            tv.setText(times.get() + "");
//                                tv.setText("打开单个格口消息：成功");
                        }
                        , throwable -> {
                            times.getAndIncrement();
                             tv.setText(times.get() + "");
//                        tv.setText(throwable.getMessage());
                        });
    }

back key - BActivity finish.

stackOverflowError

![_1540539104845](https://user-images.githubusercontent.com/12568757/47551803-bcde9d00-d935-11e8-805c-cff9e502bfaa.png)

**Comment by hzsweers** [comment]
This isn't an autodispose issue, the exception is emanating from `LambdaSubscriber` when it tries to call `onSubscribe` on the underlying onSubscribe hook, in this case likely a delegate. Seems it can't find it on the classpath judging by the `NoClassDefFoundError`, so I think that's where you'll want to investigate. Should be easy to jump in the debugger and see what's going on at runtime.
