### ISSUE TITLE
ErrorProne/Lint checks should ignore subscribe methods if returned Disposable is captured

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#284]
We can recognize these cases as "I know what I'm doing" cases

There's prior art for both of these cases in https://github.com/hzsweers/rxjava2-optionalcheckreturnvalue-checkers

**Comment by shaishavgandhi05** [comment]
Makes sense!

**Comment by dmitry-zaitsev** [comment]
As an alternative to manual management of the observer we can instead provide a controllable `ScopeProvider` which can be triggered manually. Something like that:

```
ControllableScopeProvider scopeProvider = ScopeProviders.controllableScope();

observable
    .as(autoDisposable(scopeProvider))
    .subscribeWith( /* do stuff */ )

scopeProvider.finish();
```

This would:

1. Provide a way to manage subscriptions manually.
1. Keep user in AutoDispose semantics.

**Comment by hzsweers** [comment]
I think that’d be really hard to detect in static analysis since we’d have to do data flow. I think the start with having a sort of “lenient” mode that allows you to ignore the requirement if the disposable is captured is a good start for now
