### ISSUE TITLE
Rename `ClassesWithScope` options to `TypesWithScope`

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#297]
Technically more correct, since it could be an interface too

- [ ] Lint
- [ ] Error Prone

**Comment by shaishavgandhi05** [comment]
Breaking change for error prone?

**Comment by hzsweers** [comment]
The error prone artifact never worked, but even if it did, I don't think this counts since it's just a flag it looks for in compiler args

**Comment by shaishavgandhi05** [comment]
That's true. Forgot it was a flag. 👍
