### ISSUE TITLE
Suggested fixes in static analysis

### ISSUE THREAD

**Issue by ZacSweers** [uber/AutoDispose#302]
Currently, we don't offer a suggested fix in the checkers. We _could_ potentially offer one though, as we do know the type that's requesting the scope, and could just always suggest something like

```java
Observable.just(1)
    .as(autoDisposable(DetectedScopedClass.this)) // Suggest this
    .subscribe()
```

Potential issues:
* `DetectedScopedClass.this` might be overly pedantic when it could just be `this` in most cases
* In custom scoped classes, the mechanics may be different
  * A prime example of this is RIB Workers: https://github.com/uber/RIBs/blob/master/android/libraries/rib-base/src/main/java/com/uber/rib/core/Worker.java
* We want humans to review the fix, and at least error prone's is very easy to just sort of yolo-accept the suggestion without thinking about it

On the face of it, I think these might do more harm than good. If it was more like a templated approach like structural replace, that could be different (but likely only lint-supported in the IDE)

**Comment by shaishavgandhi05** [comment]
Nice! Some additional thoughts:

* `DetectedScopedClass.this` might also be risky for Kotlin classes. We would have to do the Kotlin-esque `this@DetectedScopedClass`. In Lint, I believe we can find out if the class is Kotlin or Java so we can do this.
* For the Android scopes, we'll have to give suggestions like `AndroidLifecycleScopeProvider.from(this)`

**Comment by hzsweers** [comment]
Let's punt on this for now. Not being able to discern anything but trivial cases gives me pause on trying to do something like this

**Comment by ZacSweers** [comment]
Going to close this out since there's not a good path forward on this, happy to revisit if more proposals come up

**Comment by ShaishavGandhi** [comment]
I wanted to reopen this since I think we're in a better position to execute on this now. Since we closed on the issue, we've merged the ktx artifacts into the main artifacts. This lets us confidently suggest quick fixes for Java and Kotlin files. 

@ZacSweers What do you think?

**Comment by ZacSweers** [comment]
The original issue wasn't artifacts being split, rather this bit

> Let's punt on this for now. Not being able to discern anything but trivial cases gives me pause on trying to do something like this

Which I don't think has changed now

**Comment by ShaishavGandhi** [comment]
I think we can cover the following cases:
* When a component that contains the subscription implements ScopeProvider, we can suggest auto-fixes for both Java and Kotlin file with `as(autoDisposable(this)` or `autoDisposable(this)` 
* When a component is one of the Android lifecycle components, we can suggest auto-fixes for both Java and Kotlin files. 

That covers the cases that the current lint check already detects. Am I missing something?

**Comment by ZacSweers** [comment]
Catching missing bindings is one thing, but suggesting replacements is more
difficult. Consider fragments - there's two scopes that could be bound to.
That basically just leaves us with ScopeProvider as a safe option, but
scopes could be passed in. Or how do you know when to prefix with "this."
or "this@...". What about nested classes, which one should be used? Etc.

I'm hesitant to add something that could suggest the wrong fix.

**Comment by ShaishavGandhi** [comment]
Ok I guess that's fair. It probably serves the case for some percent of users but not for others and there is also the danger of auto-fixing something that is not right for the user (fragment lifecycle instead of the fragment view lifecycle) etc. Makes sense.
