### ISSUE TITLE
Add support for RxKotlin `subscribeBy`

### ISSUE THREAD

**Issue by shaishavgandhi05** [uber/AutoDispose#304]
`subscribeBy` should be supported by the lint check. 

I guess we don't need error-prone support since `subscribeBy` is Kotlin only and error-prone doesn't work with Kotlin (?).

**Comment by hzsweers** [comment]
I don't think it should be, it's not part of this API (I've seen 15 different subscribeBy alternatives). We could maybe open up configuration to add more subscribe methods instead

**Comment by shaishavgandhi05** [comment]
Just realized that we don't support `subscribeBy` method in the `ObservableSubscribeProxy` so that renders the issue moot. 

The configuration stuff is interesting but I fear it would be used by very few, while overcomplicating (and probably slowing down) our lint checks.

**Comment by hzsweers** [comment]
Alright, let's close this for now
