### ISSUE TITLE
com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version \u003e\u003d 26)

### ISSUE THREAD

**Issue by to686312** [uber/AutoDispose#324]
**Library version**:
compile 'com.uber.autodispose:autodispose-android-archcomponents:1.1.0'

**Repro steps or stacktrace**:
Android studio 3.2.1 directly refers to autodispose- android-based archcomponents: version 1.1.0 compile without problems but run with an error
Execution failed for task ': app: transformClassesWithDexForDevelopDebug'.
> com. Android. Build. API. The transform. TransformException: Java. Lang. RuntimeException: Java. Lang. RuntimeException: Unable to pre - dex
This is why

AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version \u003e\u003d 26)","sources":[{}]}
AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version \u003e\u003d 26)","sources":[{}]}
AGPBI: {"kind":"error","text":"2 errors; aborting","sources":[{}]}

**Comment by to686312** [comment]
Compile no error run error message appears
AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version \u003e\u003d 26)","sources":[{}]}
AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version \u003e\u003d 26)","sources":[{}]}
AGPBI: {"kind":"error","text":"2 errors; aborting","sources":[{}]}

Then appear
Execution failed for task ':app:transformClassesWithDexForDevelopDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex 'E:\.gradle\caches\modules-2\files-2.1\com.uber.autodispose\autodispose-lifecycle\1.1.0\462282fa8e17de92fcd35224b1d3d0031e849bc2\autodispose-lifecycle-1.1.0.jar' to 'D:\yilutong_code\new_driver\app\build\intermediates\transforms\dex\develop\debug\folders\1000\10\autodispose-lifecycle-1.1.0_e5804118ff38a526e2f0b368f72fed9382d301b8'

I have been searching for a long time without finding the reason. I have commented out the code that USES the dependent library, only gradle.build relies on the library

**Comment by hzsweers** [comment]
The entire first page of good results for "invokedynamic requires --min-sdk-version " all have answers :). But for posterity, the issue is because autodispose requires Java 8, which either requires use of D8 or min Sdk 26. You will need to be on java 8 as well and do one of the mentioned requirements
