### ISSUE TITLE
New lintPublish configuration

### ISSUE THREAD

**Issue by ZacSweers** [uber/AutoDispose#325]
The names in AGP 3.3 have changed a bit: https://developer.android.com/studio/releases/gradle-plugin

New lint check configuration:

> **lintChecks**: This is an existing configuration that you should use only for lint checks you want to run when building your project locally.
> **lintPublish**: Use this new configuration for library projects in which you want to include your lint checks in the published AAR. This means that projects that consume your library also apply those lint checks.
> Note: Due to this behavior change, existing library modules that upgrade to Android Gradle plugin 3.3.0 and higher need to use the new lintPublish configuration to include custom lint checks in the published AAR.

**Comment by shaishavgandhi05** [comment]
Looks like it is scheduled to be in 3.4. The release notes jumped the gun. 
Discussion [here](https://issuetracker.google.com/issues/65248347)
