### ISSUE TITLE
Saving disposable doesn't seem to be recognized by lint

### ISSUE THREAD

**Issue by ZacSweers** [uber/AutoDispose#332]
![image](https://user-images.githubusercontent.com/1361086/53301923-75561800-3826-11e9-90c2-f56a1252f091.png)

Repro: https://github.com/ZacSweers/CatchUp/blob/390106e0a7a55637895fa45152e9601cac4506f8/app/src/main/kotlin/io/sweers/catchup/ui/about/AboutActivity.kt#L326

**Comment by ZacSweers** [comment]
CC @shaishavgandhi05

**Comment by shaishavgandhi05** [comment]
Doesn't look like you have lenient mode enabled in CatchUp? https://github.com/ZacSweers/CatchUp/blob/master/gradle.properties

We don't enable lenient by default.

**Comment by ZacSweers** [comment]
Oh derp you're right
