### ISSUE TITLE
Lint error with lenient mode activated

### ISSUE THREAD

**Issue by flo5324** [uber/AutoDispose#333]
Hi,
I wanted to handle myself the lifecycle of this request, so I removed my Autodispose call but the lenient error appeared.
I do have activated lenient mode in my gradle.properties, cleaned and rebuild, still the error remains.

**Library version**: `1.1.0`

**Repro steps or stacktrace**:
![](https://puu.sh/CRuG6/ff7ce1e7ba.png)
In this case, disposables is a CompositeDisposable which I'm disposing in the onDetach function

**Comment by ZacSweers** [comment]
Can you provide a minimum reproducible sample project?

**Comment by flo5324** [comment]
I didn't found a way to reproduce it on a smaller sample but in my attempt I noticed that the lint error didn't showed up in this example with lenient disabled (except the variable never used of course)

![](https://puu.sh/CS09W/14b733cf7d.png)

**Comment by ZacSweers** [comment]
What version of studio and AGP?

**Comment by flo5324** [comment]
Android Studio 3.4 Beta 4
AGP 3.2.1

**Comment by ZacSweers** [comment]
What happens if you use non-mismatched versions? 3.2.1 is an entire minor
version behind and I'm not sure we even support it

**Comment by flo5324** [comment]
Indeed the version of AGP was the culprit, some legacy code I never thought to upgrade 
Upgrade to 3.3.1 fixed the issue
Thanks a lot ! 👍

**Comment by ZacSweers** [comment]
Great to hear, thanks! We can look to codify the minimum supported version
as a followup

**Comment by shaishavgandhi05** [comment]
Hmm technically we our minApi is set to 3.2.0 so it should've worked. But it's possible that the Android Studio version is the culprit. i.e AS 3.4 requires 3.3 or a variation of that.

**Comment by ZacSweers** [comment]
Odd. In any case, I'd be fine with raising the requirement to 3.3.x since
that's stable now

**Comment by flo5324** [comment]
Well, that's strange, the lint error is back
Still on AGP 3.3.1 and tried with AS 3.4-BETA4 and 3.3, cache cleaned and project rebuilt

Is the fact that my project is multi module may cause some trouble ? 
The example I gave in first place was in the app module, this time it's in another module

Beyond that, the error doesn't prevent me to successfully build my project

**Comment by shaishavgandhi05** [comment]
Interesting. I'd be interested in knowing which `gradle.properties` file
you put the lenient mode in. Did you put it in the project level
`gradle.properties` or is it at module level? I've seen some projects have
`gradle.properties` at module level too.

In any case, I'll try and reproduce it. I have a multi-module project and
i'll try there.

Also, you can use `@SuppressWarning("AutoDispose")` if it's bothering you.

**Comment by flo5324** [comment]
I only have a gradle.properties project-wide 
```
# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536m
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=true
autodispose.lenient=true
```

**Comment by shaishavgandhi05** [comment]
Alright so I'm able to reproduce this. It's actually looking for the module's `gradle.properties` file instead of the root project's `gradle.properties` file. 
For now, you can either `@SuppressWarning` it or you can add a module level `gradle.properties` file (not ideal I know)

I'm working on a fix. Thanks for reporting!

**Comment by flo5324** [comment]
Glad this helped !
Thank you :)

**Comment by flo5324** [comment]
Hi again !

So I updated my Autodispose dependencies to 1.2.0 and the error is still there  
Am I missing something ?

![image](https://user-images.githubusercontent.com/14941833/55945997-26d0d180-5c4c-11e9-83c4-0c9c3ed23455.png)

**Comment by shaishavgandhi05** [comment]
You'll have to add a `gradle.properties` file in your app-level. Then add the `autodispose.lenient=true` there.

project
  - app
    - gradle.properties // Add the autodispose.lenient here
  - gradle.properties

This is because while configuring Lint checks, we don't have access to the root `gradle.properties` file. 

If your project is multi-module, then you don't have to add `gradle.properties` for each module. You can simply add it to the app module and then in `lintOptions` set 
`checkDependencies true`. This is good for 2 reasons. It makes lint checks much faster and it also means that each module isn't evaluated in isolation (and can therefore use the same lint settings you've specified in app-level). 

Hope this helps.

**Comment by flo5324** [comment]
Gone for good, nice !
It might be nice for future users to explicitly indicate in the wiki that in case of a multi module project, these actions are necessary to manually handle disposables ?

Thanks again ! 😃

**Comment by flo5324** [comment]
Gone for good, nice !
It might be nice for future users to explicitly indicate in the wiki that in case of a multi module project, these actions are necessary to manually handle disposables ?

Thanks again ! 😃
