### ISSUE TITLE
AutoDisposeConverter  Set generics automatically

### ISSUE THREAD

**Issue by SunshineCui** [uber/AutoDispose#337]
```java
RetrofitFactory.getRetrofit().create(IMobileSearchApi.class)
                .getSearchSuggestion(keyWord.trim())
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .as(this.bindAutoDispose())//There is an error
                .subscribe(new Consumer<SearchSuggestionBean>() {
                    @Override
                    public void accept(SearchSuggestionBean bean) throws Exception {
                    }
                }, ErrorAction.error());
```

as
(io.reactivex.ObservableConverter<com.armdb.base.api.SearchSuggestionBean,? extends com.uber.autodispose.ObservableSubscribeProxy<java.lang.Object>>)
in Observable cannot be applied
to
(com.uber.autodispose.AutoDisposeConverter<java.lang.Object>)

**Comment by ZacSweers** [comment]
Hey @SunshineCui - I unfortunately don't know how to read that :). Any chance you could translate?

**Comment by SunshineCui** [comment]
Sorry , I have translated

**Comment by ZacSweers** [comment]
Thanks! I think I'm understanding that you're asking about being able to use a wildcard type for the `autoDisposable()` call. If so, is it the same condition as what this test does?

https://github.com/uber/AutoDispose/blob/6e1399512f132bc5052c4b1ba111debb6eb430e1/autodispose/src/test/java/com/uber/autodispose/AutoDisposeObserverTest.java#L71-L75

If possible - could you link a reproducible sample of what you're trying to do that is reporting an error?

**Comment by SunshineCui** [comment]
Thanks ! I've found out way.JDK is Wrong version.Thank you  for your answer.

> 
> 
> Thanks! I think I'm understanding that you're asking about being able to use a wildcard type for the `autoDisposable()` call. If so, is it the same condition as what this test does?
> 
> [AutoDispose/autodispose/src/test/java/com/uber/autodispose/AutoDisposeObserverTest.java](https://github.com/uber/AutoDispose/blob/6e1399512f132bc5052c4b1ba111debb6eb430e1/autodispose/src/test/java/com/uber/autodispose/AutoDisposeObserverTest.java#L71-L75)
> 
> Lines 71 to 75 in [6e13995](/uber/AutoDispose/commit/6e1399512f132bc5052c4b1ba111debb6eb430e1)
>  Observable.just(new BClass()) 
>      .as(autoDisposable(ScopeProvider.UNBOUND)) 
>      .subscribe((Consumer<AClass>) aClass -> { 
>   
>      }); 
> 
> If possible - could you link a reproducible sample of what you're trying to do that is reporting an error?
