### ISSUE TITLE
Go into the subscribe every time

### ISSUE THREAD

**Issue by githubtangchao** [uber/AutoDispose#344]
tv_get_verification.clicks()
            .throttleFirst(1, TimeUnit.SECONDS)
            .observeOn(RxSchedulers.ui)
            .autoDisposable(scope(Lifecycle.Event.ON_DESTROY))
            .subscribe {
                KeyboardktUtils.hideKeyboard(tv_get_verification)//收起键盘
                loginViewModel.registerPhone.value = et_phone.text.toString().trim()
                loginViewModel.getSMSVerifyCode(et_phone.text.toString().trim(), 2, 0)
            }

Edittext and checkbox also

First page entry，subscribe{  }  run,  i don't want  run subscribe{}
i used rxbind  and navigation fragment

**Comment by githubtangchao** [comment]
i know ,should use  .subscribeOn(RxSchedulers.ui)  not .observeOn(RxSchedulers.ui)

**Comment by ZacSweers** [comment]
Hi @githubtangchao - what's the ask here? Unfortunately your snippet isn't very actionable in its current form because we don't have enough information to help

**Comment by ZacSweers** [comment]
Closing this, please feel free to ping if you can give more info
