### ISSUE TITLE
Why not adding recipe classes to the android library?

### ISSUE THREAD

**Issue by matpag** [uber/AutoDispose#349]
Hi guys,
I've found classes located in the sample [here](https://github.com/uber/AutoDispose/tree/master/sample/src/main/kotlin/com/uber/autodispose/recipes ) really useful to start working with this library.

Why not adding them to the android ktx artifact? 
I think they could be really useful for the vast majority of developers as base classes (and who need advanced cases can still implement it's own version of `LifecycleScopeProvider`)

Glad to hear your opinions and concerns about this :)

**Comment by ZacSweers** [comment]
We try to keep the library itself fairly lean and focused API-wise. Those are a bit of a grab bag of offerings and definitely not one size fits all, so we prefer to keep them as just recipes for folks to reuse on their own if they want.

**Comment by matpag** [comment]
Thanks for the clarification :)
