### ISSUE TITLE
API proposal: improve kotlin extensions names

### ISSUE THREAD

**Issue by ZacSweers** [uber/AutoDispose#355]
Right now the Kotlin extensions all are like this

```kotlin
fooObservable
    .autoDisposable(...)
    .subscribe()
```

I've been wondering about this for awhile from a readability standpoint. In Java it made more sense because it was with `as()`

```java
myObservable
    .as(autoDisposable(...))
    .subscribe()
```

But with kotlin, maybe we can make it flow better with a different name

```kotlin
fooObservable
    .disposeWith(...)
    .subscribe()
```

Other options - `disposeOn()`, `autoDisposeWith()`, `autoDisposeOn()`, `autoDispose()`, ???

We can leave the old APIs for binary compatibility and deprecate them with a simple replace and error severity for easy migration.

Would require updating the lint as well.

**Comment by matpag** [comment]
I vote for `autoDisposeOn()` because:

- the `On` part reminds to name like "onCreate, onPause, etc..", something familiar to all android developers
- the `disposeOn` could be confused with a RxJava API

**Comment by ZacSweers** [comment]
> the On part recall to names like "onCreate, onPause, etc..", something familiar to all android developers and usually associated to lifecycle events.

AutoDispose is a JVM library first. Android's a main consumer, but we're not designing core APIs just for android familiarity

> the disposeOn could be confused with a RxJava API

Yep we're not going to go with that one after some offline discussion.

We're going to go with `autoDispose()`, matching the verb-tense of other methods like `replay()`/`share()`/`repeat()`/etc. The java name will rename `autoDisposable()`, which I think is fine considering it has slightly different semantics for what that API is doing as well. It returns a converter, while the autoDispose() APIs will just return a subscribe proxy
