### ISSUE TITLE
.as(AutoDispose.autoDisposable(AndroidLifecycleScopeProvider.from(activity)))subscribe(observer)不能同时使用

### ISSUE THREAD

**Issue by moonstr** [uber/AutoDispose#358]
private static void observer(BaseActivity activity, Observable observable, Observer 
       observer) {
       observable.subscribeOn(Schedulers.io())
                        .unsubscribeOn(Schedulers.io())
                        .observeOn(AndroidSchedulers.mainThread())         
        .as(AutoDispose.autoDisposable(AndroidLifecycleScopeProvider.from(activity)))
                .subscribe(observer)
    }

    .subscribe(observer)这部分报红无法编译通过，去掉.as或者  .subscribe(observer)就可以,是什么原因

**Comment by ShaishavGandhi** [comment]
Hey, I'm not sure what the problem is here. Unfortunately, I can't read Chinese.

**Comment by moonstr** [comment]
the code like this，the last line is red，cann‘t run it

**Comment by ZacSweers** [comment]
This is a problem with your project configuration then, we can't really assist with this

**Comment by moonstr** [comment]
I use  autoDisposable with retrofit , cann't  subscribe
