### ISSUE TITLE
Add demo scope provider for Activity

### ISSUE THREAD

**Issue by tonycosentini** [uber/AutoDispose#36]

**Comment by tadfisher** [comment]
Activities have [ActivityLifecycleCallbacks](https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks.html).

**Comment by hzsweers** [comment]
True, but we can't query the current state of the activity for lifecycle resolution :/. Most we could do would basically be to dispose on destroy, but wouldn't be able to tell if we're already after the lifecycle

**Comment by tadfisher** [comment]
Do you need to query the current state of the activity? You should get all edges of the state machine in the callbacks instance, and infer state from that. Unless there are edge cases I'm not thinking of.

**Comment by hzsweers** [comment]
Say you subscribe after onDestroy, how would you know since no callbacks would ever fire?

**Comment by microstudent** [comment]
I think some code in Glide do the similar things.
[ManagerRetriever.java#319](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/manager/RequestManagerRetriever.java#L319)
It attach a Invisible fragment to activity or fragment, as it can receive the lifecycle callback form them.

**Comment by hzsweers** [comment]
You can get callbacks, but you can't query the current state right?
