### ISSUE TITLE
Add demo scope provider for Fragment

### ISSUE THREAD

**Issue by tonycosentini** [uber/AutoDispose#37]

**Comment by tadfisher** [comment]
`FragmentLifecycleCallbacks` exists for the support library.

**Comment by hzsweers** [comment]
Same issues as https://github.com/uber/AutoDispose/issues/36#issuecomment-288888092 I think, but I'm not too familiar with the fragment callbacks. Is there a way to query the current state?

**Comment by hzsweers** [comment]
Closing in favor of #71
