### ISSUE TITLE
Should streams stop emitting when scope is in ON_PAUSE or in ON_STOP state?

### ISSUE THREAD

**Issue by niom** [uber/AutoDispose#395]
**Library version**: 1.4.0

Hi

This is more of a question than a bug.

is it by design that when we have a stream with interval operator and autodispose the stream continues to trigger even when the scope has emitted a pause and stop state?

example
```
Fragment {

   override fun onViewCreated() {
      Flowable.just(1).flatMap{ value -> 
         Flowable.interval(1, TimeUnit.SECONDS).map{value}
         .autoDispose(viewLifecycleOwner)
         .subscribe{Timber.d("Value: $value")}
      }
   }
}
``` 

When we change to the next Activity the interval continues emitting the value even though the scope it self is first in ON_PAUSE state and the ON_STOP.

behaviour does not change when using 

```
    private val scopeProvider by lazy { AndroidLifecycleScopeProvider.from(viewLifecycleOwner) }
```

and use the autoDispose(scopeProvider) instead

**Comment by ZacSweers** [comment]
Please post questions on stackoverflow with the `autodispose` tag, happy to answer there!

**Comment by niom** [comment]
https://stackoverflow.com/questions/58553972/should-streams-using-autodispose-stop-emitting-when-scope-is-in-on-pause-or-in-o
