### ISSUE TITLE
Emits and item, is this a typo?

### ISSUE THREAD

**Issue by fr373969** [uber/AutoDispose#408]
**Library version**: v1.4.0

**Repro steps or stacktrace**:
![image](https://user-images.githubusercontent.com/20133753/69583482-40831700-0f98-11ea-813e-e10e7442d2b9.png)
```emits and item``` is this a typo? Should it be "emits an item" ?

New to GitHub, this is my first post, sorry if it's a dumb question.

**Comment by ShaishavGandhi** [comment]
Yup, that's a typo. Want to send a PR to fix it?

**Comment by ShaishavGandhi** [comment]
Closed via #409
