### ISSUE TITLE
Build error with rxjava 2.2.16

### ISSUE THREAD

**Issue by Jeff11** [uber/AutoDispose#413]
Using `implementation 'com.uber.autodispose:autodispose-rxlifecycle3:1.4.0'`
with `implementation 'io.reactivex.rxjava2:rxjava:2.2.16'`
causes following error during build time, even after clean and rebuild:

```
Type com.uber.autodispose.AutoDisposeEndConsumerHelper is defined multiple times: /myproject/build/intermediates/external_libs_dex_archive/devDebug/out/94a2594e61f544fe14ef0243a831ce51d84341d2b2532e95cde3a7557a504b1e.jar:_____classes.dex, /myproject/build/intermediates/external_libs_dex_archive/devDebug/out/94a2594e61f544fe14ef0243a831ce51d84341d2b2532e95cde3a7557a504b1e_5.jar:classes.dex
```

With rxjava:2.2.15 building is no problem.

**Comment by ShaishavGandhi** [comment]
This seems like a problem with the build system you're using. Can you link a repo where you can reproduce the problem?

**Comment by Jeff11** [comment]
You were right, @ShaishavGandhi. After updating the Android Gradle plugin, this doesn't happen anymore.

**Comment by ShaishavGandhi** [comment]
Glad you got it sorted!
