### ISSUE TITLE
Obseravable called twice when completable scope.

### ISSUE THREAD

**Issue by zl910627** [uber/AutoDispose#416]
**Library version**: 1.4.0 / Rx2X
**Repro steps or stacktrace**:

`Single` has `ignoreElement()` and Maybe has `ignoreElements()`.
Above methods all converts observable to `Completable`.

If I run below, I got twice `Success` break pointed.
```Kotlin
single/maybe
    .doOnSuccess {
        print("Success!")
    }
    .doOnError {
        print("Error!")
    }
    .ignoreElement()
    .run { autoDispose(this) } // OR .run(autoDispose(ignoreElement())) with no above method.
    .subscribe()
```
**Here are my questions**
1. Is this right usage ?
2. If autodispose when source observer's success/complete/onerror rather than scope event, 
which is the best?

Thank you.

**Comment by ZacSweers** [comment]
Can you give a full repro case? Not sure what "this" is in the context above

**Comment by zl910627** [comment]
```this``` is ```completable``` instance returned by ```ignoreElement()```
http://reactivex.io/documentation/operators/ignoreelements.html
http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Single.html

```.run``` will return subscribe proxy returned by ```autoDispose(this)```

**Comment by zl910627** [comment]
**Case1**

```kotlin
Maybe.just(true) // OR Single.just(true) 
    .doOnSuccess {
        print("Success!")
    }
    .doOnError {
        print("Error!")
    }
    .ignoreElements() // OR .ignoreElement() for Single
    .run { autoDispose(this) }
    .subscribe()
```

**Case 2**
```kotlin
Maybe.just(true) // OR Single.just(true)
    .doOnSuccess {
        print("Success!")
    }
    .doOnError {
        print("Error!")
    }
    .run { autoDispose(ignoreElements()) } // OR .run { autoDispose(ignoreElement()) } for Single
    .subscribe()
```

**Comment by ShaishavGandhi** [comment]
I don't think this is the usage you're looking for here. `autoDispose` requires a CompletableSource/ScopeProvider that would signal when your lifecycle is ending, thereby disposing the stream. 

I don't know exactly what context you're using it in (server/Android app etc) but there are examples in the [sample](https://github.com/uber/AutoDispose/tree/master/sample) module

**Comment by zl910627** [comment]
I want to dispose Observables (not Stream / Publisher / Flowable) once they reaches 
- onSuccess
- onComplete
- onError
- onNext.

i.e, lifecycle for observable's processing.
This is what I am looking for.
