### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/autodispose-android_release.kotlin_module'

### ISSUE THREAD

**Issue by tankpow** [uber/AutoDispose#423]
After I updated from version 1.4.0 to version 2.0.0, a weird error emerged after rebuilding my project, this error is:
More than one file was found with OS independent path 'META-INF/autodispose-android_release.kotlin_module'.
I followed the guide from official site to update to version 2.0.0, my build.gradle file is:
/**
     * AutoDispose
     */
    final AUTO_DISPOSE_VERSION = "1.4.0"
    final AUTO_DISPOSE_2_VERSION = "2.0.0"/**/
    //* Java
    implementation "com.uber.autodispose2:autodispose:$AUTO_DISPOSE_2_VERSION"
    //* LifecycleScopeProvider
    implementation "com.uber.autodispose2:autodispose-lifecycle:$AUTO_DISPOSE_2_VERSION"
    //* Android extensions
    implementation "com.uber.autodispose2:autodispose-android:$AUTO_DISPOSE_2_VERSION"
    //* Android Architecture Components extensions
    implementation "com.uber.autodispose:autodispose-android-archcomponents:$AUTO_DISPOSE_VERSION"
    implementation "com.uber.autodispose2:autodispose-androidx-lifecycle:$AUTO_DISPOSE_2_VERSION"
    //* Androidx-Lifecycle Test extensions:
    testImplementation "com.uber.autodispose:autodispose-android-archcomponents-test:$AUTO_DISPOSE_VERSION"
    testImplementation "com.uber.autodispose2:autodispose-androidx-lifecycle-test:$AUTO_DISPOSE_2_VERSION"

    /* implementation "com.uber.autodispose:autodispose:$AUTO_DISPOSE_VERSION"
     implementation "com.uber.autodispose:autodispose-android:$AUTO_DISPOSE_VERSION"
     implementation "com.uber.autodispose:autodispose-android-archcomponents:$AUTO_DISPOSE_VERSION"
     testImplementation "com.uber.autodispose:autodispose-android-archcomponents-test:$AUTO_DISPOSE_VERSION"*/

Building is all right if uses the commented code which is of version 1.4.0, but when switch to 2.0.0, building fails.

I googled for reason but it seems no one ever encounters this error.

**Library version**:
I use Android Studio 3.6.1 with gradle 6.2.1.

**Repro steps or stacktrace**:
More than one file was found with OS independent path 'META-INF/autodispose-android_release.kotlin_module'.

**Comment by ZacSweers** [comment]
Can you paste the actual stacktrace?

**Comment by tankpow** [comment]
> Can you paste the actual stacktrace?

In my 'Build Output' console of Android Studio, the only information given is just:
'More than one file was found with OS independent path 'META-INF/autodispose-android_release.kotlin_module'.
No other information.

**Comment by ZacSweers** [comment]
Build from the command line?

**Comment by ShaishavGandhi** [comment]
Have you tried excluding the META_INF files? 
See Stackoverflow: https://stackoverflow.com/questions/44342455/more-than-one-file-was-found-with-os-independent-path-meta-inf-license

**Comment by tankpow** [comment]
> Build from the command line?

No, I build from buid menu, use 'rebuild project'. I tried first clean then build, this issue occurred. And I also 'Invalidate caches and restart', this issue still occurred.

**Comment by tankpow** [comment]
> Have you tried excluding the META_INF files?
> See Stackoverflow: https://stackoverflow.com/questions/44342455/more-than-one-file-was-found-with-os-independent-path-meta-inf-license

Thanks! It does work! 
But I still wonder how to resolve this issue somehow officially.

I added the following code in my build.gradle:
    packagingOptions {
//        exclude 'META-INF/DEPENDENCIES'
//        exclude 'META-INF/LICENSE'
//        exclude 'META-INF/LICENSE.txt'
//        exclude 'META-INF/license.txt'
//        exclude 'META-INF/NOTICE'
//        exclude 'META-INF/NOTICE.txt'
//        exclude 'META-INF/notice.txt'
//        exclude 'META-INF/ASL2.0'
        exclude("META-INF/*.kotlin_module")
    }

**Comment by ZacSweers** [comment]
Packaging options is the official way
