### ISSUE TITLE
crash  by  fragment in removing state

### ISSUE THREAD

**Issue by XuanJiAndroid** [uber/AutoDispose#425]
**Library version**: 1.4.0

**Repro steps or stacktrace**:
1. Use autodispose in two fragments
2. Two fragments in Navigation
3. Quickly enter and exit fragment
4. You can still receive subscriptions when the fragment is in the removing state
5. There are UI operations in the subscription

crash  by  fragment in removing state,use ``Lifecycle.Event.ON_DESTROY`` event

![log.png](https://user-images.githubusercontent.com/21168212/79854889-c054c680-83fc-11ea-8dec-d2ee3422e760.png)

**Comment by ZacSweers** [comment]
This isn't enough info. Please provide a reproducible test or sample project
