### ISSUE TITLE
Question: Incompatible with RxJava 2?

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [uber/AutoDispose#429]
I'm trying this out in one of my apps and I get an error when using it:

![Screenshot 2020-08-15 at 7 22 12 PM](https://user-images.githubusercontent.com/1699753/90313864-7785c800-df2d-11ea-9ecb-0e573d740588.png)

**Library version**: 2.0.0
**RxKotlin Version**: 2.4.0
**RxAndroid Version**: 2.1.1

**Steps to reproduce**:
1. Include the gradle dependencies:
```
implementation "io.reactivex.rxjava2:rxkotlin:$rx_kotlin_version"
implementation "io.reactivex.rxjava2:rxandroid:$rx_android_version"

implementation "com.uber.autodispose2:autodispose-android:$autodispose_version"
implementation "com.uber.autodispose2:autodispose-androidx-lifecycle:$autodispose_version"
implementation "com.uber.autodispose2:autodispose:$autodispose_version"
implementation "com.uber.autodispose2:autodispose-lifecycle:$autodispose_version"
```
2. Create Observables as:
```
io.reactivex.Observable.just(1).autoDispose()
io.reactivex.rxjava3.core.Observable.just(1).autoDispose()
```

As seen in the screenshot, autoDispose isn't working with the rxjava2 version of the Observable. I need this to work if I have to use auto dispose in my app since it uses dependencies like [RxAndroidBle](https://github.com/Polidea/RxAndroidBle) and several other libraries which haven't yet shifted to RxJava 3.

**Comment by ZacSweers** [comment]
Autodispose 2 is for rxjava 3. You need to use autodispose 1.x for rxjava 2

**Comment by SaifurRahmanMohsin** [comment]
Ah I see... ok. That’s slightly disappointing since the APIs differ. Thanks for the info.

**Comment by ZacSweers** [comment]
The only thing that changed was the removal of deprecated APIs. You shouldn't be using them in 1.x either.

**Comment by SaifurRahmanMohsin** [comment]
Alright, understood. Thanks!
