### ISSUE TITLE
Help ，Why the main thread is required ？

### ISSUE THREAD

**Issue by HailouWang** [uber/AutoDispose#435]
**Library version**:

**Repro steps or stacktrace**:

Hi，Dear：

here，ask for a help ：

file lie 83，Why the main thread is required ？  thx！

PS.
file：android/autodispose-androidx-lifecycle/src/main/java/autodispose2/androidx/lifecycle/LifecycleEventsObservable.java

![image](https://user-images.githubusercontent.com/30383174/92887526-22af7180-f447-11ea-925a-d988d24cf658.png)

**Comment by ZacSweers** [comment]
Because lifecycle observers should only be subscribed to on the main thread

**Comment by HailouWang** [comment]
> Because lifecycle observers should only be subscribed to on the main thread

that is why confused me. I got a demo,it works!

![image](https://user-images.githubusercontent.com/30383174/93017073-73b29780-f5f8-11ea-84b6-9f3f80cfa4de.png)

**Comment by ZacSweers** [comment]
That's not thread-safe
