### ISSUE TITLE
Obseravable called twice when completable scope. #416

### ISSUE THREAD

**Issue by zl910627** [uber/AutoDispose#442]
Would you please give me right answer for this?
https://github.com/uber/AutoDispose/issues/416

**Comment by ZacSweers** [comment]
this has no details or context

**Comment by ZacSweers** [comment]
Please don't open duplicate issues. You received a lot of feedback on the original issue, please use stackoverflow for further help

**Comment by zl910627** [comment]
thank you, stopping usage this library.

**Comment by ZacSweers** [comment]
Sounds like that's for the best 👍
