### ISSUE TITLE
Snapshots and Building from source

### ISSUE THREAD

**Issue by ber4444** [uber/AutoDispose#449]
2 questions following the "discussion" at #445:

1. why you are not releasing any snapshots, since your website links to an unmaintained but existing snapshots repo

2. when building from source, I get:
```
% find . -name "*.jar" | grep build   
./autodispose-interop/coroutines/build/libs/coroutines-2.1.0-SNAPSHOT.jar
./autodispose-interop/build/libs/autodispose-interop.jar
./test-utils/build/libs/test-utils.jar
./autodispose-lifecycle/build/libs/autodispose-lifecycle-2.1.0-SNAPSHOT.jar
./static-analysis/autodispose-error-prone/build/libs/autodispose-error-prone-2.1.0-SNAPSHOT.jar
./static-analysis/autodispose-lint/build/libs/autodispose-lint.jar
./static-analysis/build/libs/static-analysis.jar
./autodispose/build/libs/autodispose-2.1.0-SNAPSHOT.jar
```
and it is unclear how that would map to our dependencies:
```
    object AutoDispose {
        const val core = "com.uber.autodispose2:autodispose:${Versions.autoDispose}"
        const val android = "com.uber.autodispose2:autodispose-android:${Versions.autoDispose}"
        const val archcomponents = "com.uber.autodispose2:autodispose-androidx-lifecycle:${Versions.autoDispose}"
        const val archcomponentsTest = "com.uber.autodispose2:autodispose-androidx-lifecycle-test:${Versions.autoDispose}"
    }
```
note that I used ` ./gradlew jar` to build due to lack of other instructions

**Comment by ZacSweers** [comment]
> why you are not releasing any snapshots

Snapshots are here https://oss.sonatype.org/content/repositories/snapshots/com/uber/autodispose2/

> since your website links to an unmaintained but existing snapshots repo

I assume you're referring to our site still referring to the 1.0 `com.uber.autodispose` package name. Good find, we'll update this link to the new artifact.

> when building from source, I get... note that I used ./gradlew jar to build due to lack of other instructions

To build from source you could simply look at what our CI runs. This is an issue tracker for tracking project issues though, not a support platform for how to use your build system or host artifacts. Please consider taking those questions to stackoverflow or even google search.

I'll be locking this one again as I think you're being a bit petulant about this all and that goes against our [Code of Conduct](https://github.com/uber/AutoDispose/blob/main/CODE_OF_CONDUCT.md) regarding inappropriate behavior in a professional setting. Please accept the above answers and do not attempt to open new issues to pursue this further.
