### ISSUE TITLE
lint lenient mode do not support kotlin lambda/when/if expressions

### ISSUE THREAD

**Issue by sanggggg** [uber/AutoDispose#465]
**Library version**: 2.1.1

Hello, I've been trying to lint reactive expression without `autoDispose` in kotlin lambda/when/if expression with lenient mode.
```kt
kotlin.run {
    Observable.just(1).subscribe() // want to lint this expression
}
if (flag) {
    Observable.just(1).subscribe() // want to lint this expression
}
when {
    true -> Observable.just(1).subscribe() // want to lint this expression
    else -> null
}
```

However it doesn't work due to following function `AutoDisposeDetector::isExpressionValueUnused`. Current version of this function cannot detect `expression value used or not` precisely in kotlin lambda/when/if expressions

https://github.com/uber/AutoDispose/blob/311aa3cce8e30ea4f524343d201409b28e51d8f1/static-analysis/autodispose-lint/src/main/kotlin/autodispose2/lint/AutoDisposeDetector.kt#L366-L371

https://github.com/uber/AutoDispose/blob/311aa3cce8e30ea4f524343d201409b28e51d8f1/static-analysis/autodispose-lint/src/main/kotlin/autodispose2/lint/AutoDisposeDetector.kt#L400-L404

To solve this, `AutoDisposeDetector::isExpressionValueUnused` need to support these expressions
and luckily [up-to-date origin reference of the function](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/CheckResultDetector.kt;l=289;drc=c5fd7e6e7dd92bf3c57c6fe7a3a3a3ab61f4aec6) supports these expressions, so just updating function will solve this problem

**Comment by ZacSweers** [comment]
Closed in #466
