### ISSUE TITLE
LifecycleEndException handling

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#52]
Specifically, some might want to just dispose quietly (in production, or always) rather than error. Should we make this more configurable? If so, how/to what degree? Moving this discussion here from an internal one.

Currently - `LifecycleEndException` is propagated to the delegate observer's `onError`. I see two options:

A. If the delegate doesn't implement `onError`, it goes to `RxJavaPlugins` and one could filter that in a plugin hook. This would not cover cases where `onError` is implemented though. Is this fine?
B. We make this more explicitly configurable
  - Scoper overloads?
  - `RxJavaPlugins`-esque plugin system?
  - Nothing, advise just writing a custom `ScopeProvider` implementation using `ScopeUtils`?

CC @tonycosentini @AttwellBrian

**Comment by tonycosentini** [comment]
What about just advising people to potentially non-fatal them in their own `onError` plugin implementation?

**Comment by AttwellBrian** [comment]
> A. If the delegate doesn't implement onError, it goes to RxJavaPlugins and one could filter that in a plugin hook. This would not cover cases where onError is implemented though. Is this fine?

I can't think of a reason this wouldn't be fine. It was good enough for us? Do other companies implement `onError()` more than us?

**Comment by tonycosentini** [comment]
After syncing with @hzsweers in person, one idea is a plugin system for AutoDispose itself. The default implementation would just route to onError like it does currently, but would allow for custom handlers (for logging/non-fatals or whatever else makes sense for a specific app).

**Comment by hzsweers** [comment]
Cool, plugin system sounds good. @tonycosentini do you want to start a PR around that? Structure would probably be best in the same vein as `RxJavaPlugins`

**Comment by tonycosentini** [comment]
Yup, will give it a shot.

**Comment by hzsweers** [comment]
Done in #57
