### ISSUE TITLE
Use Git Versioning

### ISSUE THREAD

**Issue by PaulWoitaschek** [uber/AutoDispose#59]
Right now the only version I can see is `X.Y.Z`. (Which does not exist on maven). It would be great if you could tag releases.

**Comment by hzsweers** [comment]
Oh weird. It's supposed to be `0.1.0`, which is the only release we've done so far. Probably just slipped through from our `RELEASING` template. 

The badges in the README have the current maven versions if you were looking for them, I'll see if I can update the tag retroactively without force pushing anything

**Comment by hzsweers** [comment]
Fixed! Thanks for catching that. Make sure you run `git pull --prune --tags` to see this locally
