### ISSUE TITLE
Prepare for 0.2.0

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#68]
* **New: Kotlin artifact! (#47)**

This adds `autoDisposeWith()` extensions to RxJava types.

```kotlin
myObservable
   .doWhatever()
   .autoDisposeWith(this)
   .subscribe()
```

* **New: Plugin system! (#57)**

Modeled after RxJava's plugins, this allows you to customize the behavior of AutoDispose with lifecycle boundary checks.

```java
AutoDisposePlugins.setOutsideLifecycleHandler(t -> {
    // Swallow the exception, or rethrow it, or throw your own!
})
```

A good use case of this is, say, just silently disposing/logging observers outside of lifecycle exceptions in production but crashing on debug.

* **New: Test helpers! (#48 #49)**

Two helpers were added to simulate conditions in testing.
- `TestLifecycleScopeProvider`
  - This has two corresponding lifecycle methods: `start()` and `stop()`
- `TestScopeProvider`
  - Has just one method - `emit()`.

For testing with just the `Maybe<?>` scope, we recommend using RxJava's built-in `MaybeSubject`.

* **Fix**: Fixed a race condition where upstream wouldn't be disposed if the lifecycle emitted or error'd synchronously (i.e. was already terminated). (#57)
* **Fix**: Add missing `@CheckReturnValue` annotations to `subscribeWith` methods. (#53)

**Other tidbits:**
- Removed `@NonNull` annotations. Everything is `@NonNull` by default, and only elements 
annotated with `@Nullable` are not.
- Use of the new `java-library` plugin for gradle (#64). The RxJava dependencies are marked as `api`.
- Error prone has been integrated. Currently the annotations are just marked as `compileOnly`, but if a need arises/community wants them - we can compile them in a future version.

**Comment by hzsweers** [comment]
@tonycosentini @uber/mobile-platform-android if this all looks good, we can cut a release monday or tuesday

**Comment by AttwellBrian** [comment]
> New: Plugin system! (#57)

Nice idea. Why do we need `setOutsideLifecycleHandler` when we already have the ability to RxPlugins to suppress this errors with RxPlugins?

**Comment by tonycosentini** [comment]
It's a bit easier to integrate. If you take a look at the current
implementation in our error handler, it's a pretty fragile process to
properly pull out the lifecycle exceptions when they are already wrapped in
multiple exceptions.

**Comment by hzsweers** [comment]
Released!
