### ISSUE TITLE
how to do a bindUntil ?

### ISSUE THREAD

**Issue by blackberry2016** [uber/AutoDispose#72]
Corresponding events works well , but how can i do a bindUntil just like rxLife ?

**Comment by hzsweers** [comment]
Can you be more specific? If you have a traditional stream of lifecycle events, you can simulate something like a "bindUntil" by just doing something like this:

```java
myObservable
    .to(new ObservableScoper<>(lifecycleEvents
        .filter(...)
        .firstElement())
    .subscribe();
```

**Comment by UsherBaby** [comment]
it works, thanks @blackberry2016

**Comment by blackberry2016** [comment]
@h2rashee lifecycleEvents？ is that a Maybe ？

**Comment by hzsweers** [comment]
lifecycle events could be an observable, calling `firstElement()` returns a `Maybe` and you'd filter on whatever event you're looking for

**Comment by blackberry2016** [comment]
@hzsweers In my case , LifeScopeProvider is an Acitivyt  and lifecycle() method returns a BehaviorSubject.
```java
myObservable
    .to(new ObservableScoper<>(lifecycle()
        .filter(...)
        .firstElement())
    .subscribe();
```
the filter() is not called !

**Comment by hzsweers** [comment]
do you have sample code? It's difficult to help from that snippet alone

**Comment by h2rashee** [comment]
@blackberry2016 Am I missing how I'm involved in this ticket?

**Comment by blackberry2016** [comment]
@hzsweers sorry , now i can't . i will post some tonight !

**Comment by blackberry2016** [comment]
@hzsweers it works.

**Comment by blackberry2016** [comment]
@hzsweers When resubcribe , it seems will immediately call 
'''
new ObservableScoper<>(lifecycle()
        .filter(...)
        .firstElement()
'''
